<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Test', 'doctrine');

/**
 * BaseTest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $chk_1
 * @property integer $chk_2
 * 
 * @method integer getId()    Returns the current record's "id" value
 * @method enum    getChk1()  Returns the current record's "chk_1" value
 * @method integer getChk2()  Returns the current record's "chk_2" value
 * @method Test    setId()    Sets the current record's "id" value
 * @method Test    setChk1()  Sets the current record's "chk_1" value
 * @method Test    setChk2()  Sets the current record's "chk_2" value
 * 
 * @package    symfonypractice
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('test');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('chk_1', 'enum', 3, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'yes',
              1 => 'no',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('chk_2', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}