<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Product', 'doctrine');

/**
 * BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property string $name
 * @property integer $price
 * @property text $description
 * @property string $image
 * @property Doctrine_Collection $ProductDetails
 * @property Doctrine_Collection $ProductAttribute
 * @property Doctrine_Collection $DummyCart
 * 
 * @method integer             getProductId()        Returns the current record's "product_id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method integer             getPrice()            Returns the current record's "price" value
 * @method text                getDescription()      Returns the current record's "description" value
 * @method string              getImage()            Returns the current record's "image" value
 * @method Doctrine_Collection getProductDetails()   Returns the current record's "ProductDetails" collection
 * @method Doctrine_Collection getProductAttribute() Returns the current record's "ProductAttribute" collection
 * @method Doctrine_Collection getDummyCart()        Returns the current record's "DummyCart" collection
 * @method Product             setProductId()        Sets the current record's "product_id" value
 * @method Product             setName()             Sets the current record's "name" value
 * @method Product             setPrice()            Sets the current record's "price" value
 * @method Product             setDescription()      Sets the current record's "description" value
 * @method Product             setImage()            Sets the current record's "image" value
 * @method Product             setProductDetails()   Sets the current record's "ProductDetails" collection
 * @method Product             setProductAttribute() Sets the current record's "ProductAttribute" collection
 * @method Product             setDummyCart()        Sets the current record's "DummyCart" collection
 * 
 * @package    symfonypractice
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product');
        $this->hasColumn('product_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('price', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('image', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProductDetails', array(
             'local' => 'product_id',
             'foreign' => 'product_id'));

        $this->hasMany('ProductAttribute', array(
             'local' => 'product_id',
             'foreign' => 'product_id'));

        $this->hasMany('DummyCart', array(
             'local' => 'product_id',
             'foreign' => 'product_id'));
    }
}