<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Attribute', 'doctrine');

/**
 * BaseAttribute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $attribute_id
 * @property string $name
 * @property AttributeValues $AttributeValues
 * @property Doctrine_Collection $ProductAttribute
 * 
 * @method integer             getAttributeId()      Returns the current record's "attribute_id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method AttributeValues     getAttributeValues()  Returns the current record's "AttributeValues" value
 * @method Doctrine_Collection getProductAttribute() Returns the current record's "ProductAttribute" collection
 * @method Attribute           setAttributeId()      Sets the current record's "attribute_id" value
 * @method Attribute           setName()             Sets the current record's "name" value
 * @method Attribute           setAttributeValues()  Sets the current record's "AttributeValues" value
 * @method Attribute           setProductAttribute() Sets the current record's "ProductAttribute" collection
 * 
 * @package    symfonypractice
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAttribute extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attribute');
        $this->hasColumn('attribute_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AttributeValues', array(
             'local' => 'attribute_id',
             'foreign' => 'attribute_id'));

        $this->hasMany('ProductAttribute', array(
             'local' => 'attribute_id',
             'foreign' => 'attribute_id'));
    }
}