<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('client', 'doctrine');

/**
 * Baseclient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $username
 * @property string $password
 * @property Doctrine_Collection $clientDetail
 * 
 * @method string              getUsername()     Returns the current record's "username" value
 * @method string              getPassword()     Returns the current record's "password" value
 * @method Doctrine_Collection getClientDetail() Returns the current record's "clientDetail" collection
 * @method client              setUsername()     Sets the current record's "username" value
 * @method client              setPassword()     Sets the current record's "password" value
 * @method client              setClientDetail() Sets the current record's "clientDetail" collection
 * 
 * @package    symfonypractice
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseclient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client');
        $this->hasColumn('username', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('password', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('clientDetail', array(
             'local' => 'id',
             'foreign' => 'id_client'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}