<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Content', 'doctrine');

/**
 * BaseContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_content
 * @property string $content_type
 * @property string $content_title
 * @property string $image
 * @property enum $enable
 * 
 * @method integer getIdContent()     Returns the current record's "id_content" value
 * @method string  getContentType()   Returns the current record's "content_type" value
 * @method string  getContentTitle()  Returns the current record's "content_title" value
 * @method string  getImage()         Returns the current record's "image" value
 * @method enum    getEnable()        Returns the current record's "enable" value
 * @method Content setIdContent()     Sets the current record's "id_content" value
 * @method Content setContentType()   Sets the current record's "content_type" value
 * @method Content setContentTitle()  Sets the current record's "content_title" value
 * @method Content setImage()         Sets the current record's "image" value
 * @method Content setEnable()        Sets the current record's "enable" value
 * 
 * @package    symfonypractice
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content');
        $this->hasColumn('id_content', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('content_type', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('content_title', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('enable', 'enum', 3, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'yes',
              1 => 'no',
             ),
             'default' => 'yes',
             'notnull' => false,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'content_title',
              1 => 'image',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}