<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DummyCart', 'doctrine');

/**
 * BaseDummyCart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product_id
 * @property integer $user_id
 * @property integer $quantity
 * @property integer $price
 * @property Product $Product
 * @property User $User
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method integer   getProductId()  Returns the current record's "product_id" value
 * @method integer   getUserId()     Returns the current record's "user_id" value
 * @method integer   getQuantity()   Returns the current record's "quantity" value
 * @method integer   getPrice()      Returns the current record's "price" value
 * @method Product   getProduct()    Returns the current record's "Product" value
 * @method User      getUser()       Returns the current record's "User" value
 * @method DummyCart setId()         Sets the current record's "id" value
 * @method DummyCart setProductId()  Sets the current record's "product_id" value
 * @method DummyCart setUserId()     Sets the current record's "user_id" value
 * @method DummyCart setQuantity()   Sets the current record's "quantity" value
 * @method DummyCart setPrice()      Sets the current record's "price" value
 * @method DummyCart setProduct()    Sets the current record's "Product" value
 * @method DummyCart setUser()       Sets the current record's "User" value
 * 
 * @package    symfonypractice
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDummyCart extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dummy_cart');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('product_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('quantity', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('price', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'product_id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'cascade' => array(
             0 => 'delete',
             )));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}