# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   home.html
  param: { module: login, action: @login }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
product_add:
  url:          products.html
  param:        { module: products, action: add }
product_edit:
  url:         :id_edit/edit_products.html
  param:        { module: products, action: add }  
product_list:
  url:          products_list.html
  param:        { module: products, action: list }
product_attribute:
  url:          setAttribute.html
  param:        { module: products, action: productAttributeList }
product_attribute_add:
  url:           AddAttribute.html
  param:        { module: products, action: productAttributeList }  
category_add:
  url:          category.html
  param:        { module: catagory, action: add }
category_edit:
  url:         :id_edit/edit_category.html
  param:        { module: catagory, action: add }  
category_list:
  url:          category_list.html
  param:        { module: catagory, action: list }
Change_password:
  url:          Change_password.html
  param:        { module: login, action: changePassword }  
gallary:
  url:          gallary.html
  param:        { module: products, action: gallary }  
login:
  url:          login.html
  param:        { module: login, action: login }   
home:
  url:          adminHome.html
  param:        { module: login, action: home }  
AttributeAdd:
  url:          AttributeAdd.html
  param:        { module: attribute, action: attributeAdd } 
AttributeList:
  url:          AttributeList.html
  param:        { module: attribute, action: attributeList }   
AttributeEdit:
  url:          AttributeEdit.html
  param:        { module: attribute, action: attributeAdd } 
attribute_add:
  url:          attribute_add.html
  param:        { module: attribute, action: add } 
attribute_list:
  url:          attribute_list.html
  param:        { module: attribute, action: list }   
attribute_edit:
  url:          attribute_edit.html
  param:        { module: attribute, action: add } 

content:
  url:          content.html
  param:        { module: content, action: list }  
content_add:
  url:          content_add.html
  param:        { module: content, action: add }    
content_edit:
  url:          id_edit:/content_edit.html
  param:        { module: content, action: add }   
mergeForms:
  url:          id_edit:/client.html
  param:        { module: demos, action: index }     
  
  
  
  