<?php
/**
 * Admin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Myfirstproject
 * @subpackage Model
 * @author     viren   <virendav.vitrainee@gmail.com>     
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
 
class AdminTable extends Doctrine_Table
{
    /**
    * Executes getInstance function
    *
    * @author Dattesh viren   <virendav.vitrainee@gmail.com>     
    * @access public
    * @return object
    *
    */
  
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Admin');
    }
}