<?php

/**
 * clientDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Myfirstproject
 * @subpackage Model
 * @author     viren   <virendav.vitrainee@gmail.com>     
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
 
class ContentTable extends Doctrine_Table
{
 /**
  * Executes getInstance function to get instance
  *
  * @author viren   <virendav.vitrainee@gmail.com>    
  * @access public
  * @return object
  */
    
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Content');
  }
    
 /**
  * Executes listing function to get list of jobs.
  *
  * @param String $sortBy    stores sorting order
  * @param String $searchBy  stores value for searching
  * @param String $culture   stores culture
  *
  * @author viren   <virendav.vitrainee@gmail.com>    
  * @access public
  *
  * @return array
  */
  public function listingContent($sortBy, $searchBy, $culture)
  { 
    if($sortBy =='' && $searchBy =='')
      return false;
    else
    {  
    $query = Doctrine_Query::create()
          ->select('u.*, pd.*')
          ->from('Content u')
          ->leftjoin('u.Translation pd')
          ->where('pd.lang = ? ', $culture);
      if($searchBy != '')
        $query -> andWhere('u.content_type LIKE ? ', $searchBy.'%');
    
    $query -> orderBy('u.content_type '.$sortBy); 
      return $query;
    } 
  }
}