<?php

/**
 * DummyCartTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Myfirstproject
 * @subpackage Model
 * @author     viren   <virendav.vitrainee@gmail.com>     
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
 
class DummyCartTable extends Doctrine_Table
{
    /**
    * Executes getInstance function to get instance
    *
    * @author viren   <virendav.vitrainee@gmail.com>    
    * @access public
    *
    * @return object
    */
    
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DummyCart');
    }
    
  /**
    * Executes listing function to get listing
    *
    * @param String $userId stores user id
    *
    * @author viren   <virendav.vitrainee@gmail.com>    
    * @access public
    *
    * @return array
    */
    
  public function listing($userId)
  {
    $query = Doctrine_Query::create()
        ->select('p.*,d.*')
        ->from('DummyCart d')
        ->leftjoin('d.Product p')
        ->where('d.user_id = ? ', $userId)
        ->andWhere('d.product_id = p.product_id')
        ->orderBy('p.name ASC')
        ->fetchArray();
    return $query;       
  }
}