<?php

/**
* ProductTable
* This class has been auto-generated by the Doctrine ORM Framework
* 
* @package    Myfirstproject
* @subpackage Model
* @author     viren   <virendav.vitrainee@gmail.com>      
* @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
*/

class ProductTable extends Doctrine_Table
{
    
 /**
  * Executes getInstance to get instance
  *
  * @author viren   <virendav.vitrainee@gmail.com>    
  * @access public
  *
  * @return object
  *
  */   
    
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Product');
  }
    
 /**
  * Executes listing function to get list of jobs.
  *
  * @param String $id stores product id
  *
  * @author viren   <virendav.vitrainee@gmail.com>    
  * @access public
  *
  * @return array
  */
    
  public function listing($id)
  {
    if(!empty($id)) 
    {   
      $Product = Doctrine_Query::create()
          ->select('u.*,pd.*')
          ->from('Product u')
          ->leftjoin('u.ProductDetails pd')
          ->where('u.product_id = '.$id)
          ->fetchArray();      
      return $Product;
    }
    else
      return false;   
  }
  
 /**
  * Executes listingProduct function to get list of jobs.
  *
  * @author viren   <virendav.vitrainee@gmail.com>    
  * @access public
  *
  * @return array
  */
  public function listingProduct($sortBy, $searchBy)
  {
    if($sortBy =='' && $searchBy =='')  
      return false;
    else
    {   
      $query = Doctrine_Query::create()
          ->from('Product a');
      if($searchBy != '')
        $query -> where('a.name LIKE ? ', $searchBy.'%');
		
	  $query -> orderBy('a.name '.$sortBy);
	  
      return $query;
    }
  }
  
 /**
  * Executes getAllProductOptions function
  *
  * @author viren   <virendav.vitrainee@gmail.com>    
  * @access public
  *
  * @return String
  *
  */ 
  
  public static function getAllProductOptions()
  {
    $q = Doctrine_Core::getTable('Product')
      ->createQuery('c')
      ->orderBy('c.product_id ASC')
      ->limit(sfConfig::get('app_limit'));
    return $q;    
  }
}