<?php

/**
* User 
* This class has been auto-generated by the Doctrine ORM Framework
* 
* @package    Myfirstproject
* @subpackage Model
* @author     viren   <virendav.vitrainee@gmail.com> 
* @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
*/
 
class User extends BaseUser
{
 /**
  * Executes loginUser function check user authentication.
  *
  * @param String $user stores username
  * @param String $pass stores password
  *
  * @author viren   <virendav.vitrainee@gmail.com>    
  * @access public
  *
  * @return array
  */
  
  public function loginUser($user, $pass)
  { 
    if($user == '' || $pass == '')
      return false;
    else
      $q = Doctrine_Core::getTable('user')
          ->createQuery('c')
          ->where('c.username = ?', $user)
          ->andWhere('c.password = ?', $pass)
          ->orderBy('c.username ASC');
      $user = $q->fetchArray();
      return $user;  
  } 
}
