<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('dummy_cart', 'created_at');
        $this->removeColumn('dummy_cart', 'updated_at');
        $this->addColumn('product_attributes', 'image', 'varchar', '255', array(
             ));
    }

    public function down()
    {
        $this->addColumn('dummy_cart', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('dummy_cart', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->removeColumn('product_attributes', 'image');
    }
}