<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product_attributes', 'image', 'varchar', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('product_attributes', 'image');
    }
}