<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('client', 'user_name');
        $this->addColumn('client', 'username', 'string', '20', array(
             ));
    }

    public function down()
    {
        $this->addColumn('client', 'user_name', 'string', '20', array(
             ));
        $this->removeColumn('client', 'username');
    }
}