<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('client', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_name' => 
             array(
              'type' => 'string',
              'length' => '20',
             ),
             'password' => 
             array(
              'type' => 'string',
              'length' => '20',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('client_detail', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'id_client' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'varchar',
              'length' => '255',
             ),
             'email' => 
             array(
              'type' => 'varchar',
              'length' => '255',
             ),
             'address' => 
             array(
              'type' => 'varchar',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('dummy_cart', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('dummy_cart', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('client');
        $this->dropTable('client_detail');
        $this->removeColumn('dummy_cart', 'created_at');
        $this->removeColumn('dummy_cart', 'updated_at');
    }
}