<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('client_detail', 'client_detail_id_client_client_id', array(
             'name' => 'client_detail_id_client_client_id',
             'local' => 'id_client',
             'foreign' => 'id',
             'foreignTable' => 'client',
             ));
        $this->addIndex('client_detail', 'client_detail_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('client_detail', 'client_detail_id_client_client_id');
        $this->removeIndex('client_detail', 'client_detail_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
    }
}